### ISSUE TITLE
PermissionError: [WinError 5] Access is denied: 'fairseq\\examples'

### ISSUE THREAD

**Issue by sriprad** [kakaobrain/pororo#15]
## How to reproduce
Hi Team,

Thanks for creating this. Looks great. However when i tried to run the pip install pororo.
Its giving me the below error. can you help?

PermissionError: [WinError 5] Access is denied: 'fairseq\\examples'
Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 136, in do_setup
      setup(
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\__init__.py", line 147, in _install
_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 60, in fetch_b
uild_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "c:\program files\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\program files\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\program files\python38\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 149, in get_re
quires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_b
uild_requires
      self.run_setup()
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-build-env-eaqbi4ax\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_se
tup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  PermissionError: [WinError 5] Access is denied: 'fairseq\\examples'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' 'c:\program files\python38\lib\site-packages\pip\_vendor\pep517\_in_p
rocess.py' get_requires_for_build_wheel 'C:\Users\Public\Documents\Wondershare\CreatorTemp\tmptfw4z7_p' Check the logs for full command output.
-

## Environment

-

**Comment by sooftware** [comment]
Hi @sriprad !! Can you tell me more about the environment you experimented on?  
It looks like a Windows environment, is that right?

**Comment by Huffon** [comment]
There is a problem with the Windows support of the `fairseq` on which `Pororo` relies.
Unfortunately, until `fairseq`'s Windows support issue is resolved, it seems difficult to use `Pororo`.

It is recommended to use a Linux machine such as Ubuntu.
Thank you.

**Comment by sriprad** [comment]
Hi @sooftware . thank you for the reply. Yes it's a window's env.
@Huffon  thank you. Will try that.
