### ISSUE TITLE
설치중에 아래와 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by fspanda** [kakaobrain/pororo#5]
# Environment 

OS :  Window 10
Python Version : 3.7.7

```

Collecting pororo
  Using cached pororo-0.3.1-py3-none-any.whl (211 kB)
Collecting marisa-trie
  Using cached marisa-trie-0.7.5.tar.gz (270 kB)
Collecting whoosh
  Using cached Whoosh-2.7.4-py2.py3-none-any.whl (468 kB)
Collecting sentence-transformers==0.4.1.2
  Using cached sentence-transformers-0.4.1.2.tar.gz (64 kB)
Collecting kss
  Using cached kss-2.4.0.1-py3-none-any.whl (66 kB)
Collecting nltk==3.5
  Using cached nltk-3.5.zip (1.4 MB)
Collecting wget
  Using cached wget-3.2.zip (10 kB)
Collecting transformers>=4.0.0
  Using cached transformers-4.2.2-py3-none-any.whl (1.8 MB)
Collecting g2p-en
  Using cached g2p_en-2.1.0-py3-none-any.whl (3.1 MB)
Collecting fairseq==0.10.2
  Using cached fairseq-0.10.2.tar.gz (938 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\python.exe' 'c:\programdata\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\Y_BANG~1\AppData\Local\Temp\tmp6_ujjzw6'
       cwd: C:\Users\Y_BANG~1\AppData\Local\Temp\pip-install-g1p7bpee\fairseq_7bcacca07705475f8c7fc3346d13a310
  Complete output (31 lines):
  Traceback (most recent call last):
    File "setup.py", line 214, in <module>
      do_setup(package_data)
    File "setup.py", line 191, in do_setup
      zip_safe=False,
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\__init__.py", line 152, in setup
      _install_setup_requires(attrs)
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 60, in fetch_build_eggs
      raise SetupRequirementsError(specifier_list)
  setuptools.build_meta.SetupRequirementsError: ['cython', 'numpy', 'setuptools>=18.0']
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\Y_BANG~1\AppData\Local\Temp\pip-build-env-030fno3d\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 217, in <module>
      os.unlink(fairseq_examples)
  PermissionError: [WinError 5] 액세스가 거부되었습니다: 'fairseq\\examples'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/02/59/1f466d82d64482e2809a167e0067979c23057b3752e668537d5ff24453c9/fairseq-0.10.2.tar.gz#sha256=45b90d8ccc3f5a4623a523fe2d0465f54413d03fd1ec9a9d7af0461148ca1a68 (from https://pypi.org/simple/fairseq/). Command errored out with exit status 1: 'c:\programdata\anaconda3\python.exe' 'c:\programdata\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\Y_BANG~1\AppData\Local\Temp\tmp6_ujjzw6' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement fairseq==0.10.2 (from pororo)
ERROR: No matching distribution found for fairseq==0.10.2
```

**Comment by hyunwoongko** [comment]
관리자 권한으로 cmd를 실행하시고 다시 시도해보실 수 있으실까요?

**Comment by fspanda** [comment]
네 그렇게 했는데도 똑같은 에러가 발생합니다.

**Comment by Huffon** [comment]
```console
pip install --upgrade pip
pip install fairseq
```

진행하면 어떠실까요?

**Comment by fspanda** [comment]
pip 최신으로 업그레이드 하고 
fairseq 인스톨을 진행해 봤는데 10.2, 10.1 버전은 마찬가지 에러가 나서 
10.0 버전이 설치되서 pororo 설치는 안되네요.
fairseq 이슈로 가봤는데 저랑 비슷한 문제가 있는 사람이 있지만 명확한 해결 답은 안준 것 같습니다. 
pororo 이슈라기 보다는 fairseq 이슈인 것 같네요.

**Comment by Huffon** [comment]
`fairseq>=0.10.0` 버전에서 정상 동작하는지 확인 후, 의존성 정보를 업데이트하겠습니다 :)

**Comment by Huffon** [comment]
`fairseq==0.10.0` 버전에서 라이브러리가 정상 동작하는지 확인한 결과,
`torch` 버전 호환이 되지 않는 관계로 정상 동작하지 않는 것으로 파악되었습니다.

Windows 운영체제에서 최소 기능이라도 제공을 할 수 있으면 좋겠지만,
현재 `fairseq`의 Windows 지원 문제가 해결되기 이전까지 활용이 어려울 것 같습니다.

Ubuntu 등의 Linux 계열 머신을 활용하는 것을 추천드립니다.
감사합니다.
