### ISSUE TITLE
Dependency parsing에서의 java_gateway error

### ISSUE THREAD

**Issue by midannii** [kakaobrain/pororo#70]
## Code

```python
from koalanlp import API
from koalanlp.proc import Parser
from koalanlp.Util import initialize, finalize

initialize(hnn='LATEST')
parser = Parser(API.HNN)

parser('단일철근이나 철선, 다중 스터럽 또는 용접철망의 수직철근 등이 사용될 수 있다.')
```

위와 같은 코드를 실행하려는데, 아래와 같은 에러가 발생합니다 

RAM 청소 등 다양한 구글링을 거쳤지만 같은 에러가 반복됩니다 ㅜㅜ

```
[py4j.java_gateway] An error occurred while trying to connect to the Java server (127.0.0.1:55589)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 982, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1120, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 982, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1120, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/koalanlp/proc.py", line 238, in __call__
    return self.analyze(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/koalanlp/proc.py", line 213, in analyze
    result += py_list(self.__api.analyze(string(paragraph)), item_converter=Sentence.fromJava)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/koalanlp/jvm.py", line 100, in string
    return class_of('java.lang.String')(s) if s is not None else None
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1572, in __call__
    answer = self._gateway_client.send_command(command)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1036, in send_command
    connection = self._get_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 984, in _get_connection
    connection = self._create_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 990, in _create_connection
    connection.start()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/py4j/java_gateway.py", line 1132, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:55589)
```

## Environment

- OS : Mac
- Python version : 3.9.6, 3.7
- CPU/GPU : CPU
- Misc. :

**Comment by coding-Benny** [comment]
안녕하세요. 에러 로그를 보니 Python 3.7을 사용하셨을 때의 메시지로 보이는데, KoalaNLP의 [README](https://github.com/koalanlp/python-support#dependency-%EC%B6%94%EA%B0%80)를 살펴보니 아래와 같이 적혀있는 것을 발견했습니다.
> Python 3.7은 일부 의존 라이브러리의 문제로 인해 사용이 불가능합니다. 해당 라이브러리에서 문제를 해결하기 전까지는 3.6 이하를 사용해주세요.

한번 파이썬 버전을 변경하여 작업해 보시겠어요? 참고로 저는 권장하는 파이썬 버전은 아니지만 아래 환경에서 동일한 코드를 실행시켰을 때 에러가 발생하지 않았습니다!
- OS: Mac
- Python version: 3.8.10
- Java version: 11
![image](https://user-images.githubusercontent.com/51183274/134295100-a7f74427-24dd-443f-bee0-b6f4a0ff094f.png)

**Comment by midannii** [comment]
말씀해주신 부분 참고하여 잘 진행했습니다! 감사합니다:)
