### ISSUE TITLE
HTTPError when downloading a model

### ISSUE THREAD

**Issue by rexlow** [kakaobrain/pororo#8]
I was trying to run the OCR example but got this error.

**Environment**

- macOS Big Sur 11.11
- Python 3.8.6

```
Darwin Rex-MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

**Code**

```
from pororo import Pororo
ocr = Pororo(task="ocr", lang="en")
result = ocr('./test.jpeg')
```

**Trackback**

```
Traceback (most recent call last):
  File "oc.py", line 9, in <module>
    ocr = Pororo(task="ocr", lang="en")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pororo/pororo.py", line 196, in __new__
    task_module = SUPPORTED_TASKS[task](
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pororo/tasks/optical_character_recognition.py", line 87, in load
    det_model_path = download_or_load(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pororo/tasks/utils/download_utils.py", line 322, in download_or_load
    return download_or_load_misc(info)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pororo/tasks/utils/download_utils.py", line 219, in download_or_load_misc
    type_dir = download_from_url(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pororo/tasks/utils/download_utils.py", line 288, in download_from_url
    wget.download(url, type_dir)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by hyunwoongko** [comment]
Hello.

I solved problem just now. 
could you try again?

**Comment by rexlow** [comment]
I just tried again, it works, thanks!
